<?php

__('Everywhere', 'chatbro');
__('Front page only', 'chatbro');
__('Everywhere except those listed', 'chatbro');
__('Only the listed pages', 'chatbro');
__("Specify pages by using their paths. Enter one path per line. The '*' character is a wildcard. Example paths are /2012/10/my-post for a single post and /2012/* for a group of posts. The path should always start with a forward slash(/).", 'chatbro');
__('User profile path', 'chatbro');
__('Enable shortcodes', 'chatbro');
__('Invalid chat key', 'chatbro');
__("ChatBro plugin", "chatbro");
__("Yes, delete them all", "chatbro");
__("Shortcode copied", "chatbro");
__("Chat has been deleted", "chatbro");
__("Chat has been updated", "chatbro");
__("Are you sure you want to delete the chat?", "chatbro");
__("My chats", "chatbro");
__("ChatBro profile", "chatbro");
__("Prices", "chatbro");
__("Plugin Settings", "chatbro");
__("Help", "chatbro");
__("Create a new chat", "chatbro");
__("Please refresh the page to access the profile.", "chatbro");
__("The service ChatBro is currently unavailable. Please try again later.", "chatbro");
__("ChatBro is a web messenger that can be synchronized with Telegram and VK.", "chatbro");
__("Our site", "chatbro");
__("Documentation", "chatbro");
__("FAQ", "chatbro");
__("Contacts", "chatbro");
__("Contact us if you have any questions.", "chatbro");
__("Loading...", "chatbro");
__("You are about to change the Account ID", "chatbro");
__("Please be noticed that your current profile and chats are identified by your Account ID and if you lose it there will be no way to restore access to you current profile unless you have registered an account at <a href='https://www.chatbro.com'>ChatBro.com</a>. Please make sure that you have saved your old Account ID and fully understand what are you going to do.", "chatbro");
__("Your old Account ID: <span></span>", "chatbro");
__("Cancel", "chatbro");
__("Change Account ID", "chatbro");
__("Save Changes", "chatbro");
__("Edit", "chatbro");
__("Delete", "chatbro");
__("Online", "chatbro");
__("Approx costs", "chatbro");
__("Copy shortcode", "chatbro");
__("Dynamic creation", "chatbro");
__("Display chat to guests", "chatbro");
__("Show popup chat", "chatbro");
__("Save", "chatbro");
__("Dynamic creation", "chatbro");
__("Created at", "chatbro");
__("You have no chats yet.", "chatbro");
__("Something went wrong. Try again later.", "chatbro");
__("Settings was successfuly saved", "chatbro");
__("Bad request", "chatbro");
__("The credentials provided is incorrect or invalid.", "chatbro");
__("This chat has child chats. By deleting it, you will delete them too. This action cannot be undone. Are you sure you want to continue?", "chatbro");
__("Shortcodes", "chatbro");
__("Use shortcodes for flexible chat customization. It allows you to insert the chat on a specific page or even in a specific block on the page. Simply click the 'Copy Shortcode' button and paste the code into the desired block. If the button is not present, make sure that the 'Shortcodes enabled' parameter on the 'Plugin settings' tab is enabled.", "chatbro");
__("Such a chat will ignore the 'Show popup chat' parameter and will appear in any case.", "chatbro");
__("Shortcode example", "chatbro");
__("Supported shortcode attributes", "chatbro");
__("<em><b>id</b></em> &ndash; chat ID. For the main chat, this parameter should be omitted.", "chatbro");
__("<em><b>static</b></em> &ndash; static not movable chat widget (default <em>true</em>).", "chatbro");
__("<em><b>registered_only</b></em> &ndash; display chat widget to logged in users only (default <em>false</em>). If this attribute is explicitly set it precedes the global <em>'Display chat to guests'</em> setting value.", "chatbro");
__("For example you want different chats for different pages of your site. In case you have video hosting site you can make different chat for each video. Generate these chats on the fly using the child chats feature.", "chatbro");
__("Child chat is a chat that uses the settings of another (parent) chat. This is done in order to automate the process of creating your chats.", "chatbro");
__("How to use it?", "chatbro");
__("Simply click on the 'Dynamic creation' button, and then paste this shortcode in the right place. When the page loads, the chat will be created automatically.", "chatbro");
__("Child chats are inserted through a special shortcode:", "chatbro");
__("<em><b>id</b></em> &ndash; ID of parent chat. The chat will copy the settings of this chat.", "chatbro");
__("<em><b>child</b></em> &ndash; tells the system to create a child chat.", "chatbro");
__("<em><b>title</b></em> &ndash; unique title that to be used as chat identifier. This means that this chat will be associated with this title. 2 shortcodes with the same title will load 2 identical chats.", "chatbro");
__("<em><b>ext_id</b></em> &ndash; optional additional indentificator. If you want to have two or more different chats with equal titles add this parameter. Timestamp is perfect for this.", "chatbro");
__("What do child chats inherit?", "chatbro");
__("Visual settings;", "chatbro");
__("Authorization settings;", "chatbro");
__("Privacy settings;;", "chatbro");
__("Message filter function;", "chatbro");
__("Tariff, balance.", "chatbro");
__("Synchronization with messengers", "chatbro");
__("Chatbro allows you to synchronize messages between the website and popular messengers like Telegram or VK.", "chatbro");
__("How to sync up Telegram group/supergroup?", "chatbro");
__("Add @ChatbroBot to telegram group or supergroup. The bot will send a link in a private message where you can link the web chat and the telegram group/supergroup. If you don't have contact with our bot until this moment, it will not be able to send you a private message and will send a link to the group/supergroup.", "chatbro");
__("How to sync up the Telegram channel?", "chatbro");
__("Add @ChatbroBot to the telegram channel as an administrator and type '/sync' in the channel. The bot will send a sync link to this channel.", "chatbro");
__("What if I want to use my bot with a specific name?", "chatbro");
__("You can easily add your own bot.", "chatbro");
__("Follow the instructions.", "chatbro");
__("How to sync VK conversation with the web chat?", "chatbro");
__("Detail instruction", "chatbro");
__("how to add bot and sync it.", "chatbro");
__("How to make automatic synchronization?", "chatbro");
__("Message filtering", "chatbro");
__("You can set up flexible message filtering on our server side or use a send delay.", "chatbro");
__("How to configure?", "chatbro");
__("Go to the chat editor, then the 'Restrictions' block, and click 'Edit function'. In the editor that opens, at the bottom right, there will be a general example button.", "chatbro");
__("Spoofing protection", "chatbro");
__("Spoofing is the situation when a person or a program successfully masks under another way of falsifying data and receives illegal benefits. For example, in the chat one person can write under the guise of another. The spoofing protection excludes such situations. Chatbro allows you to make sure that the chat is not displayed on other sites besides yours and exclude sending messages from other resources.", "chatbro");
__("This feature is enabled and configured in the plugin by default.", "chatbro");
__("Your current profile and chats are associated with your account ID. Please keep it in a secure place. In the future, when removing the plugin or transitioning to another CMS, you'll be able to easily restore all your chats and account.", "chatbro");
__("Remember that deleting the plugin will erase information about the account ID. If you want to temporarily pause the plugin, simply uncheck 'Plugin enabled.'", "chatbro");
__("How to transfer ChatBro account to plugin?", "chatbro");
__("To transfer an existing account from ChatBro to the plugin, you can follow these steps:", "chatbro");
__("1. Merge Chats from Plugin with ChatBro Profile:", "chatbro");
__("1. In the plugin, navigate to the 'ChatBro profile' tab.", "chatbro");
__("2. In the 'Linked accounts' section, click the 'Connect' button.", "chatbro");
__("3. Authenticate with the required ChatBro account.", "chatbro");
__("4. This will merge your accounts, allowing you to administer your chats through the chatbro.com website account.", "chatbro");
__("2. Integrate Chatbro.com Account into the Plugin:", "chatbro");
__("1. Log in to the chatbro.com website.", "chatbro");
__("2. Go to your profile settings.", "chatbro");
__("3. In the 'API' section, click the 'Enable' button.", "chatbro");
__("4. Copy the generated API keys.", "chatbro");
__("5. Open the plugin settings and go to the third tab.", "chatbro");
__("6. Paste the copied API keys into the corresponding fields.", "chatbro");
__("7. Save the changes.", "chatbro");
__("By following these steps, you should be able to transfer your existing ChatBro account to the plugin and seamlessly manage your chats.", "chatbro");
__("Invalid show popup chat option value", "chatbro");
__("Plugin enabled", "chatbro");
__("Account ID", "chatbro");
__("Account secret", "chatbro");
__("Shortcodes enabled", "chatbro");
__("Everywhere", "chatbro");
__("Front page only", "chatbro");
__("Everywhere except those listed", "chatbro");
__("Only the listed pages", "chatbro");
__("Disabled", "chatbro");
__("Specify pages by using their paths. The '*' character is a wildcard. Example paths are /2012/10/my-post for a single post and /2012/* for a group of posts. Enter one path per line. Example:", "chatbro");
__("The session has expired or is invalid. Please refresh the page.", "chatbro");
